{
 "title": "Churn-App Overview",
 "panels": [
  {
   "title": "Req /s  (1 m avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{endpoint=\"/predict\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error rate (5 m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(api_requests_total{endpoint=\"/predict\",http_status!~\"2..\"}[5m])) / sum(rate(api_requests_total{endpoint=\"/predict\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_predict_seconds_bucket{endpoint=\"/predict\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Rows written (last run)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "batch_rows_written" }
   ]
  },
  {
   "title": "Batch duration (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "targets": [
    { "expr": "batch_job_seconds_sum" }
   ]
  }
 ]
}