global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "churn-api"
    static_configs:
      - targets: ["churn-api:9999"]

  - job_name: "churn_batch"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]  # or "node-exporter:9100" if not using host mode

